language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  # https://travis-ci.org/siznax/wptools
  - nosetests tests/test_basic.py
  # https://coveralls.io/github/siznax/wptools
  - coverage run --source=wptools setup.py test
after_success:
  coveralls
